---

- name: "Ensure required packages are installed for NodeJS"
  apt: name=$item state=latest update_cache=yes
  with_items: ${node_dependencies}
  tags:
    - nodejs

- name: "Add NodeJS repository to sources"
  action: apt_repository repo=${node_ppa}
  tags:
    - nodejs

- name: "Update APT package cache"
  action: apt update_cache=yes
  tags:
    - nodejs

- name: "Install NodeJS"
  action: apt pkg=nodejs state=latest install_recommends=yes
  tags:
    - nodejs

- name: "Install global NodeJS modules"
  action: npm name=${item} state=latest global=true
  with_items: ${node_modules}
  tags:
    - nodejs
