---

- name: "Add 10gen key"
  action: apt_key id=${mongodb.key} url=${mongodb.key_url} state=present
  tags:
    - mongodb

# Adds 10gen source
- name: "Copy mongodb.list to /etc/apt/sources.list.d/"
  action: copy src=files/mongodb.list dest=/etc/apt/sources.list.d/mongodb.list
  tags:
    - mongodb

# Makes sure it worked
- name: "Make sure mongodb.list is present"
  action: file path=/etc/apt/sources.list.d/mongodb.list state=file
  tags:
    - mongodb

- name: "Update APT package cache"
  action: apt update_cache=yes
  tags:
    - mongodb

- name: "Install MongoDB"
  action: apt pkg=${mongodb.package} force=yes
  tags:
    - mongodb

# Start MongoDB service
- name: "Ensure MongoDB is running"
  action: service name=${mongodb.service} state=started
  tags:
    - mongodb

